(()=>{
  const $=id=>document.getElementById(id);
  const providers=()=>window.PROVIDERS||[];
  const careLabels={general:"General / internal medicine",dental:"Dental",screening:"Health screening",cardiology:"Cardiology",cancer:"Cancer / second opinion",womens:"Women's health / ART"};
  const params=()=>new URLSearchParams(location.search);
  const current=()=>{const q=params();return{audience:q.get("audience")||"visitor",care:q.get("care")||"general",language:q.get("language")||"all",area:q.get("area")||"all"};};
  const providerFromPreview=()=>{const boxes=[...($("handoffPreview")?.querySelectorAll(".handoff-box")||[])];const box=boxes.find(x=>x.querySelector("small")?.textContent?.includes("SELECTED ACCESS PROFILE"));const name=box?.querySelector("b")?.textContent?.trim();return providers().find(p=>p.name===name)||null;};
  const evidence=p=>(p?.expertiseEvidence||[]).slice(0,12).map(e=>typeof e==="string"?{type:"legacy",label:e,status:"unverified"}:{type:e.type||"legacy",label:e.label||e.name||"Untitled evidence",status:e.evidenceStatus||e.status||"unverified",sourceUrl:e.sourceUrl||e.source||null,verifiedDate:e.verifiedDate||e.verified||null});
  const known=v=>{const s=String(v||"").trim().toLowerCase();return Boolean(s)&&!s.includes("unknown")&&!s.includes("needs verification");};
  function costSnapshot(p){if(!p)return null;const rows=[["Medical",p.medicalCost],["Interpreter",p.interpreterCost],["Coordinator",p.coordinatorCost]],recorded=rows.filter(([,v])=>known(v)).length;return{recorded,total:3,missing:rows.filter(([,v])=>!known(v)).map(([k])=>k),publishedCount:Array.isArray(p.publishedCosts)?p.publishedCosts.length:0,completeness:recorded===3?"components-recorded":recorded?"partial":"needs-verification",priceTransparency:p.priceTransparency||"unknown",provenance:p.recordStatus==="official-source-verified"?"official-source-checked":"demo-unverified"};}
  function mount(){
    const panel=$("stepHandoff");if(!panel||$("demoInquiry"))return;
    const section=document.createElement("section");section.id="demoInquiry";section.className="demo-inquiry";
    section.innerHTML=`<div class="demo-inquiry-head"><div><small>JAPAN HEALTH INQUIRY</small><b>Continue with the context already collected.</b><span>The demo submits to the existing Japan Health intake endpoint. AMECA remains only a downstream placeholder when a live partner route is configured.</span></div></div><form id="demoInquiryForm"><div class="demo-inquiry-grid"><label>Name<input id="demoLeadName" autocomplete="name" required placeholder="Your name"></label><label>Email<input id="demoLeadEmail" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>Timing<select id="demoLeadTiming"><option value="flexible">Flexible / exploring</option><option value="within-2-weeks">Within 2 weeks</option><option value="within-1-month">Within 1 month</option><option value="within-3-months">Within 3 months</option></select></label><label>Preferred contact<select id="demoLeadContact"><option value="email">Email</option><option value="either">Email or messaging</option></select></label></div><label>Additional logistics context<textarea id="demoLeadNotes" placeholder="Optional: timing, documents, language support or scheduling context. Avoid unnecessary sensitive medical details in this demo."></textarea></label><label class="demo-inquiry-consent"><input id="demoLeadConsent" type="checkbox" required><span>I agree that Japan Health may share this coordination inquiry with a Japan-based downstream partner if needed. This is not medical advice.</span></label><button class="btn primary" type="submit" id="demoInquirySubmit">Send demo inquiry</button><p id="demoInquiryStatus" role="status" aria-live="polite"></p></form>`;
    $("demoHandoffSummary")?.insertAdjacentElement("afterend",section) || $("handoffPreview")?.insertAdjacentElement("afterend",section);
    $("demoInquiryForm")?.addEventListener("submit",submit);
  }
  async function submit(e){
    e.preventDefault();const status=$("demoInquiryStatus"),btn=$("demoInquirySubmit"),s=current(),p=providerFromPreview();
    const payload={name:$("demoLeadName").value.trim(),email:$("demoLeadEmail").value.trim(),audience:s.audience,city:"Tokyo",need:careLabels[s.care]||s.care,notes:$("demoLeadNotes").value.trim(),timeframe:$("demoLeadTiming").value,contactPreference:$("demoLeadContact").value,partnerConsent:$("demoLeadConsent").checked,providerId:p?.id||null,providerName:p?.name||null,providerContext:p?{provenance:p.recordStatus==="official-source-verified"?"official-source-checked":"demo-unverified",evidence:evidence(p),accessSnapshot:{score:null,breakdown:{communication:null,booking:null,eligibility:null,cost:null},priceTransparency:p.priceTransparency||"unknown"}}:null,costSnapshot:costSnapshot(p),sourcePage:location.pathname+location.search,partnerRoute:"ameca",accessConstraints:{q:careLabels[s.care]||s.care,audience:s.audience,city:"Tokyo",language:s.language,coordinator:"all",referral:"all"},createdAt:new Date().toISOString()};
    if(status)status.textContent="Sending…";if(btn)btn.disabled=true;
    try{const r=await fetch("/api/lead",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});let j={};try{j=await r.json();}catch(_){}if(!r.ok)throw new Error(j.error||"Inquiry could not be accepted.");if(status)status.innerHTML=j.forwarded?`<b>Inquiry sent.</b> Reference: ${j.requestId||"available"}.`:`<b>Demo inquiry accepted.</b> ${j.requestId?`Reference: ${j.requestId}. `:""}No live downstream partner was contacted.`;const complete=$("stepComplete");if(complete){complete.querySelector("h2").textContent="The inquiry reached a clear product endpoint.";complete.querySelector("p").textContent=j.forwarded?"Japan Health carried the selected scenario and provider context into the coordination intake endpoint and a downstream route was available.":"Japan Health carried the selected scenario and provider context into the coordination intake endpoint. The downstream partner remains a demo placeholder, so no live partner was contacted.";}}
    catch(err){if(status)status.textContent=(err.message||"Inquiry could not be accepted.")+" Your entries remain in the form so you can retry.";}finally{if(btn)btn.disabled=false;}
  }
  const observer=new MutationObserver(()=>requestAnimationFrame(mount));observer.observe(document.querySelector("main")||document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});
  const style=document.createElement("style");style.id="demo-inquiry-styles";style.textContent=`.demo-inquiry{margin-top:12px;padding:16px;border:1px solid #cfddea;border-radius:14px;background:#fff}.demo-inquiry-head small,.demo-inquiry-head b,.demo-inquiry-head span{display:block}.demo-inquiry-head small{font-size:7px;font-weight:900;letter-spacing:.06em;color:#718295}.demo-inquiry-head b{font-size:11px;color:#173c5f;margin:3px 0}.demo-inquiry-head span{font-size:8px;line-height:1.45;color:#607487}.demo-inquiry form{margin-top:12px}.demo-inquiry-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.demo-inquiry label{display:block;font-size:8px;font-weight:800;color:#52687c}.demo-inquiry input,.demo-inquiry select,.demo-inquiry textarea{width:100%;margin-top:4px}.demo-inquiry textarea{min-height:78px;resize:vertical}.demo-inquiry-consent{display:flex!important;gap:8px;align-items:flex-start;margin:10px 0}.demo-inquiry-consent input{width:auto;margin-top:2px}.demo-inquiry-consent span{font-size:8px;line-height:1.45;font-weight:500}.demo-inquiry #demoInquiryStatus{min-height:18px;margin:8px 0 0;font-size:8px;line-height:1.45;color:#52687c}@media(max-width:600px){.demo-inquiry-grid{grid-template-columns:1fr}.demo-inquiry .btn{width:100%}}`;
  document.head.appendChild(style);mount();
})();