-- Japan Health provider database schema
-- Stores public provider-access facts only. Do not store patient inquiries or sensitive health data here.

create table if not exists public.providers (
  id text primary key,
  data jsonb not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_data_shape check (
    data ? 'id'
    and data ? 'name'
    and data->>'id' = id
  )
);

create index if not exists providers_city_idx
  on public.providers ((data->>'city'));

create index if not exists providers_area_idx
  on public.providers ((data->>'area'));

create index if not exists providers_record_status_idx
  on public.providers ((data->>'recordStatus'));

create index if not exists providers_specialties_gin_idx
  on public.providers using gin ((data->'specialties'));

-- Field-level evidence history. One provider can have many claims, each tied to a source.
-- This is what lets Japan Health distinguish "English listed" from physician English,
-- interpreter availability, insurance acceptance, referral rules, etc. without overwriting history.
create table if not exists public.provider_evidence (
  id bigint generated by default as identity primary key,
  provider_id text not null references public.providers(id) on delete cascade,
  field_key text not null,
  value_text text,
  status text not null default 'verified' check (status in ('verified','unknown','stale','disputed')),
  source_url text not null,
  source_label text,
  checked_at timestamptz not null,
  valid_until timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists provider_evidence_provider_idx
  on public.provider_evidence (provider_id, field_key, checked_at desc);
create index if not exists provider_evidence_status_idx
  on public.provider_evidence (status, checked_at desc);

-- Published cost facts only. Unknown prices stay absent/unknown rather than estimated.
-- Amounts are stored as integer minor units (for JPY this is yen) to avoid floating-point errors.
create table if not exists public.provider_cost_items (
  id bigint generated by default as identity primary key,
  provider_id text not null references public.providers(id) on delete cascade,
  item_key text not null,
  label text not null,
  amount_minor bigint,
  currency char(3) not null default 'JPY',
  price_type text not null default 'published' check (price_type in ('published','range','from','unknown')),
  included_items text,
  excluded_items text,
  source_url text not null,
  checked_at timestamptz not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists provider_cost_items_provider_idx
  on public.provider_cost_items (provider_id, active, checked_at desc);

alter table public.providers enable row level security;
alter table public.provider_evidence enable row level security;
alter table public.provider_cost_items enable row level security;

-- No public RLS policy is created intentionally.
-- The Vercel server-side /api/providers endpoint reads with SUPABASE_SERVICE_ROLE_KEY.
-- Browser clients must never receive the service-role key.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists providers_set_updated_at on public.providers;
create trigger providers_set_updated_at
before update on public.providers
for each row execute function public.set_updated_at();
